#!/bin/sh
### BEGIN INIT INFO
# Provides:    doorbot
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start doorbot
### END INIT INFO

PROC='/root/Doorbot/doorbot.py'
PIDFILE=/var/run/doorbot.pid

case "$1" in
  start)
    start-stop-daemon --start --chdir /root/Doorbot --pidfile $PIDFILE --exec $PROC
  ;;
  stop)
    start-stop-daemon --stop --pidfile $PIDFILE --retry TERM/10/KILL/5
  ;;
  restart|reload|force-reload)
    $0 stop
    $0 start
  ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 2
  ;;
esac
exit 0

