#!/bin/bash

cd /root/Doorbot

if [ "$1" != 1 ]; then
  screen -dmS doorbot $0 1
else
  echo Starting doorbot...
  echo $$ >/var/run/rundoorbot.pid
  while true; do
    ./doorbot.py -r0
    echo Doorbot exited. Restarting shortly...
    echo Restarting doorbot |nc -q1 172.31.24.101 12345
    sleep 5
  done
fi

